/**
 * Generates every icon Play and the PWA installer need, from one vector
 * source. Run with `npm run icons`.
 *
 * The mark is the ledger itself: entry lines on accounting paper with the
 * bottom rule struck in fountain-pen blue — the total line. It reads at
 * 48px, which is the only size that really matters on a home screen.
 */
import sharp from 'sharp';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const out = resolve(root, 'public/icons');
mkdirSync(out, { recursive: true });

const INK = '#14201a';
const PAPER = '#eaf0e6';
const BAND = '#c9d9c2';
const BLUE = '#5b86f0';

/** @param {number} pad fraction of the canvas kept clear at each edge */
const markSvg = (size, pad, ground) => {
  const s = size;
  const inset = s * pad;
  const w = s - inset * 2;
  // Four entry lines; the last is the struck total.
  const lines = [0.86, 0.62, 0.74, 0.5];
  const barH = w * 0.108;
  const gap = (w - barH * 4) / 3.4;
  const top = inset + (w - (barH * 4 + gap * 3)) / 2;

  const bars = lines
    .map((frac, i) => {
      const y = top + i * (barH + gap);
      const bw = w * frac;
      const fill = i === 3 ? BLUE : i % 2 === 0 ? PAPER : BAND;
      return `<rect x="${inset}" y="${y}" width="${bw}" height="${barH}" rx="${barH / 2}" fill="${fill}"/>`;
    })
    .join('');

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${s}" height="${s}" viewBox="0 0 ${s} ${s}">
  ${ground}
  ${bars}
</svg>`;
};

const rounded = (s) =>
  `<rect width="${s}" height="${s}" rx="${s * 0.22}" fill="${INK}"/>`;
const square = (s) => `<rect width="${s}" height="${s}" fill="${INK}"/>`;

const jobs = [
  // Standard icons: rounded tile, generous but full-bleed artwork.
  ['icon-192.png', 192, 0.17, rounded(192)],
  ['icon-512.png', 512, 0.17, rounded(512)],
  // Maskable: the launcher may crop to a circle, so keep art inside the
  // safe zone (the central 80%) and let the ground run to the edges.
  ['maskable-192.png', 192, 0.26, square(192)],
  ['maskable-512.png', 512, 0.26, square(512)],
  // Play Console store icon.
  ['play-icon-512.png', 512, 0.17, rounded(512)],
];

for (const [name, size, pad, ground] of jobs) {
  const svg = markSvg(size, pad, ground);
  await sharp(Buffer.from(svg)).png().toFile(resolve(out, name));
  console.log('wrote', name);
}

// Apple touch icon (no transparency, iOS rounds it itself).
await sharp(Buffer.from(markSvg(180, 0.17, square(180))))
  .png()
  .toFile(resolve(out, 'apple-touch-icon.png'));
console.log('wrote apple-touch-icon.png');

// favicon.ico at the three sizes browsers actually pick from.
await sharp(Buffer.from(markSvg(48, 0.14, rounded(48))))
  .png()
  .toFile(resolve(root, 'public/favicon.png'));
console.log('wrote favicon.png');

/* ---------------------------------------------------------------------------
   Play feature graphic — 1024x500, shown at the top of the store listing.
   No screenshot content here: Play rejects feature graphics that are just
   shrunken screenshots, and text near the edges gets cropped on some layouts.
   --------------------------------------------------------------------------- */
const feature = `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="500" viewBox="0 0 1024 500">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#14201a"/>
      <stop offset="1" stop-color="#1d3329"/>
    </linearGradient>
  </defs>
  <rect width="1024" height="500" fill="url(#g)"/>
  ${Array.from({ length: 10 }, (_, i) => {
    const y = 26 + i * 48;
    return `<rect x="0" y="${y}" width="1024" height="24" fill="#ffffff" opacity="0.022"/>`;
  }).join('')}
  <g transform="translate(84,150)">
    ${[0.86, 0.62, 0.74, 0.5]
      .map((frac, i) => {
        const y = i * 52;
        const fill = i === 3 ? BLUE : i % 2 === 0 ? PAPER : BAND;
        return `<rect x="0" y="${y}" width="${196 * frac}" height="22" rx="11" fill="${fill}"/>`;
      })
      .join('')}
  </g>
  <text x="340" y="228" font-family="Georgia, 'Times New Roman', serif" font-size="72"
        font-weight="700" fill="#f2f6f0" letter-spacing="-1.5">Split Ledger</text>
  <text x="344" y="286" font-family="Helvetica, Arial, sans-serif" font-size="27"
        fill="#a9bcb0">Share expenses. Settle up in the fewest payments.</text>
</svg>`;
await sharp(Buffer.from(feature)).png().toFile(resolve(out, 'play-feature-1024x500.png'));
console.log('wrote play-feature-1024x500.png');

writeFileSync(
  resolve(out, 'README.txt'),
  [
    'Generated by scripts/make-icons.mjs — run `npm run icons` to rebuild.',
    '',
    'icon-192 / icon-512          PWA install icons (purpose: any)',
    'maskable-192 / maskable-512  Android adaptive icons (art inside the 80% safe zone)',
    'play-icon-512                Play Console > Store listing > App icon',
    'play-feature-1024x500        Play Console > Store listing > Feature graphic',
    'apple-touch-icon             iOS home screen',
    '',
    'Screenshots are NOT generated here — Play wants them from the running app.',
    'See scripts/screenshots.mjs once the app is deployed.',
  ].join('\n'),
);
console.log('wrote README.txt');
